// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace signature.Migrations
{
    [DbContext(typeof(SignatureDbContext))]
    partial class SignatureDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Signer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ConsentAgreedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<double>("PositionX")
                        .HasColumnType("float");

                    b.Property<double>("PositionY")
                        .HasColumnType("float");

                    b.Property<string>("SignatureImage")
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("SignatureRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("SignatureRequestId");

                    b.ToTable("Signers", (string)null);
                });

            modelBuilder.Entity("SignatureRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SignatureRequests", (string)null);
                });

            modelBuilder.Entity("Entities.Signer", b =>
                {
                    b.HasOne("SignatureRequest", null)
                        .WithMany("Signers")
                        .HasForeignKey("SignatureRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DigitalCertificate", "Certificate", b1 =>
                        {
                            b1.Property<Guid>("SignerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("NotAfter")
                                .HasColumnType("datetime2")
                                .HasColumnName("CertNotAfter");

                            b1.Property<DateTime>("NotBefore")
                                .HasColumnType("datetime2")
                                .HasColumnName("CertNotBefore");

                            b1.Property<string>("Subject")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("CertSubject");

                            b1.Property<string>("Thumbprint")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("CertThumbprint");

                            b1.HasKey("SignerId");

                            b1.ToTable("Signers");

                            b1.WithOwner()
                                .HasForeignKey("SignerId");
                        });

                    b.OwnsOne("FechaSigner", "FechaSigner", b1 =>
                        {
                            b1.Property<Guid>("SignerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FechaValue")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("FechaValue");

                            b1.Property<double>("HeightFechaSigner")
                                .HasColumnType("float")
                                .HasColumnName("HeightFechaSigner");

                            b1.Property<double>("PositionXFechaSigner")
                                .HasColumnType("float")
                                .HasColumnName("PositionXFechaSigner");

                            b1.Property<double>("PositionYFechaSigner")
                                .HasColumnType("float")
                                .HasColumnName("PositionYFechaSigner");

                            b1.Property<double>("WidthFechaSigner")
                                .HasColumnType("float")
                                .HasColumnName("WidthFechaSigner");

                            b1.HasKey("SignerId");

                            b1.ToTable("Signers");

                            b1.WithOwner()
                                .HasForeignKey("SignerId");
                        });

                    b.OwnsOne("IntialEntity", "InitialEntity", b1 =>
                        {
                            b1.Property<Guid>("SignerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("HeightIntial")
                                .HasColumnType("float")
                                .HasColumnName("HeightIntial");

                            b1.Property<string>("InitalValue")
                                .IsRequired()
                                .HasMaxLength(4)
                                .HasColumnType("nvarchar(4)")
                                .HasColumnName("InitialValue");

                            b1.Property<double>("PositionXIntial")
                                .HasColumnType("float")
                                .HasColumnName("PositionXIntial");

                            b1.Property<double>("PositionYIntial")
                                .HasColumnType("float")
                                .HasColumnName("PositionYIntial");

                            b1.Property<double>("WidthIntial")
                                .HasColumnType("float")
                                .HasColumnName("WidthIntial");

                            b1.HasKey("SignerId");

                            b1.ToTable("Signers");

                            b1.WithOwner()
                                .HasForeignKey("SignerId");
                        });

                    b.Navigation("Certificate");

                    b.Navigation("FechaSigner");

                    b.Navigation("InitialEntity");
                });

            modelBuilder.Entity("SignatureRequest", b =>
                {
                    b.Navigation("Signers");
                });
#pragma warning restore 612, 618
        }
    }
}
