FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["EmailServices/EmailServices.csproj", "EmailServices/"]
COPY ["SharedLibrary/SharedLibrary.csproj", "SharedLibrary/"]
RUN dotnet restore "EmailServices/EmailServices.csproj"
COPY . .
WORKDIR "/src/EmailServices"
RUN dotnet build "EmailServices.csproj" -c Release -o /app/build
RUN dotnet tools install --global dotnet-ef --version 9.0.0 \
    && export PATH="$PATH:/root/.dotnet/tools" \
    && dotnet ef database update --project ../EmailServices/EmailServices.csproj 


FROM build AS publish
RUN dotnet publish "EmailServices.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .


ENTRYPOINT ["dotnet", "EmailServices.dll"]