FROM mcr.microsoft.com/dotnet/sdk:9.0 AS migrator

WORKDIR /src
COPY . .

RUN dotnet tool install --global dotnet-ef --version 9.0.0
ENV PATH="${PATH}:/root/.dotnet/tools"

WORKDIR /src/signature
ENTRYPOINT ["dotnet", "ef", "database", "update"]
